---
abstract: 'simple, non-Moose interface to the Stripe API'
author:
  - 'Grant Street Group <developers@grantstreet.com>'
  - 'David F. Houghton <dfhoughton@gmail.com>'
build_requires:
  DateTime: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::More: '0.88'
  autodie: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-Stripe-Simple
no_index: {}
requires:
  Devel::StackTrace: '0'
  Exporter: '0'
  HTTP::Request::Common: '0'
  JSON: '0'
  LWP::UserAgent: '0'
  MIME::Base64: '0'
  Scalar::Util: '0'
  URI::Escape: '0'
  constant: '0'
  overload: '0'
  parent: '0'
  perl: v5.10.0
  strict: '0'
  warnings: '0'
version: '0.001'
